---
title: "reference.Rmd"
author: "Samuel Chan"
date: "3/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exploratory Data Analysis

```{r}
confirmed_w <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")

deaths_w <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")

recovered_w <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv")
```



Old (outdated:)
```{r eval=FALSE}
confirmed_w <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv")

deaths_w <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv")

recovered_w <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv")
```



```{r}
library(tidyr)
cleanSingle <- function(x){
  x %>%
    select(-Province.State, -Lat, -Long) %>% 
    gather(key="date", value="Value", -Country.Region) %>% 
    group_by(Country.Region, date) %>% 
    summarise("Value"=sum(Value)) %>% 
    ungroup() %>% 
    select(date, "country"=Country.Region, Value) %>% 
    mutate(date, date=as.Date(substring(date, 2, nchar(date)),"%m.%d.%y"))
}
```


```{r}
res <- list(confirmed_w, deaths_w, recovered_w) %>% 
  lapply(cleanSingle) %>% 
  purrr::reduce(left_join,by = c("date", "country"))

colnames(res)[3:5] <- c("confirmed", "deaths", "recovered")
```

```{r}
tail(res[res$country == "US", ])
```


```{r}
unique(res$country)
```


```{r}
tail(res)
```
```{r}
write.csv(res, "covid_clean.csv")
```

```{r}
range(res$date)
```



```{r}
reslong <- res %>% reshape2::melt(
               id.vars=c("date", "country"),
               measured.vars=c("confirmed", "recovered", "dead"))
tail(reslong)
```



```{r}
library(ggplot2)
ggplot(data=subset(reslong, country == "Singapore"), aes(x=date, y=value, col=variable)) +
  geom_smooth(method="loess", formula="y~x")
```

